In [1]:
import pandas as pd
import numpy as np

In [3]:
file_path = "./data/06_(문제)타이타닉_분류_데이터셋.csv"
df = pd.read_csv(file_path)
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     891 non-null    int64  
 1   pclass       891 non-null    int64  
 2   sex          891 non-null    object 
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64  
 5   parch        891 non-null    int64  
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object 
 8   class        891 non-null    object 
 9   who          891 non-null    object 
 10  adult_male   891 non-null    bool   
 11  deck         203 non-null    object 
 12  embark_town  889 non-null    object 
 13  alive        891 non-null    object 
 14  alone        891 non-null    bool   
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB


In [65]:
pd.get_dummies(df)

survived  pclass   age  sibsp  parch     fare  adult_male  alone  psex  \
0         0.0     3.0  22.0    1.0    0.0   7.2500         1.0    0.0   0.0   
1         1.0     1.0  38.0    1.0    0.0  71.2833         0.0    0.0   0.0   
2         1.0     3.0  26.0    0.0    0.0   7.9250         0.0    1.0   0.0   
3         1.0     1.0  35.0    1.0    0.0  53.1000         0.0    0.0   0.0   
4         0.0     3.0  35.0    0.0    0.0   8.0500         1.0    1.0   0.0   
..        ...     ...   ...    ...    ...      ...         ...    ...   ...   
891       0.0     0.0   0.0    0.0    0.0   0.0000         0.0    0.0   0.0   
892       1.0     1.0   1.0    1.0    1.0   1.0000         1.0    1.0   1.0   
893       NaN     NaN   NaN    NaN    NaN      NaN         NaN    NaN   NaN   
894       1.0     1.0   1.0    1.0    1.0   1.0000         1.0    1.0   1.0   
895       NaN     NaN   NaN    NaN    NaN      NaN         NaN    NaN   NaN   

     female  ...  deck_G  embark_town_0  embark_town_1  embark_town_Cherbourg  \
0       NaN  ...       0              0              0                      0   
1       NaN  ...       0              0              0                      1   
2       NaN  ...       0              0              0                      0   
3       NaN  ...       0              0              0                      0   
4       NaN  ...       0              0              0                      0   
..      ...  ...     ...            ...            ...                    ...   
891     NaN  ...       0              1              0                      0   
892     NaN  ...       0              0              1                      0   
893     1.0  ...       0              0              0                      0   
894     1.0  ...       0              0              1                      0   
895     1.0  ...       0              0              0                      0   

     embark_town_Queenstown  embark_town_Southampton  alive_0  alive_1  \
0                         0                        1        0        0   
1                         0                        0        0        0   
2                         0                        1        0        0   
3                         0                        1        0        0   
4                         0                        1        0        0   
..                      ...                      ...      ...      ...   
891                       0                        0        1        0   
892                       0                        0        0        1   
893                       0                        0        0        0   
894                       0                        0        0        1   
895                       0                        0        0        0   

     alive_no  alive_yes  
0           1          0  
1           0          1  
2           0          1  
3           0          1  
4           1          0  
..        ...        ...  
891         0          0  
892         0          0  
893         0          0  
894         0          0  
895         0          0  

[896 rows x 48 columns]

In [ ]:
# pclass	객실 등급
# survived	생존 유무
# sex	성별
# age	나이
# sibsp	형제 혹은 부부의 수
# parch	부모 혹은 자녀의 수
# fare	지불한 요금

In [5]:
# 분류분석 : 객실 등급, 성별, 나이, 지불한 요금에 따른 생존률

### 독립변수 : 객실등급. 성별, 나이, 지불한요금
### 종속변수 : 생존률

In [16]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [22]:
### 결측치 제거
df_new = df[['survived','pclass', 'sex', 'age','fare']].dropna().reset_index(drop=True)
df_new

survived  pclass     sex   age     fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
709         0       3  female  39.0  29.1250
710         0       2    male  27.0  13.0000
711         1       1  female  19.0  30.0000
712         1       1    male  26.0  30.0000
713         0       3    male  32.0   7.7500

[714 rows x 5 columns]

In [26]:
df_input = df_new[['pclass', 'sex', 'age','fare']].to_numpy()
df_input

array([[3, 'male', 22.0, 7.25],
       [1, 'female', 38.0, 71.2833],
       [3, 'female', 26.0, 7.925],
       ...,
       [1, 'female', 19.0, 30.0],
       [1, 'male', 26.0, 30.0],
       [3, 'male', 32.0, 7.75]], dtype=object)

In [29]:
df_target = df_new['survived'].to_numpy()
df_target

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,

In [34]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = \
    train_test_split(df_input, df_input, random_state=42)
    

print(train_input.shape)
print(train_target.shape)
print(test_input.shape)
print(test_target.shape)

(535, 4)
(535, 4)
(179, 4)
(179, 4)


In [35]:
train_input

array([[2, 'male', 35.0, 10.5],
       [3, 'female', 5.0, 19.2583],
       [3, 'female', 32.0, 15.5],
       ...,
       [1, 'female', 41.0, 134.5],
       [3, 'male', 33.0, 20.525],
       [3, 'male', 33.0, 7.8958]], dtype=object)